import Head from 'next/head';
import { Navbar } from '@ui';

interface Props {
  children: JSX.Element | JSX.Element[];
}

export const RootLayout: React.FC<Props > = ({ children }) => {
  return (
    <>
      <Head>
        <title>Poke-Vote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="bg-slate-600 text-white h-screen overflow-hidden">
        {children}
      </main>
    </>
  );
};
