import Head from 'next/head';
import { Navbar } from '@ui';

export const RootLayout: React.FC<{
  children: JSX.Element | JSX.Element[];
}> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Poke-Vote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-700 h-screen text-white">
        <Navbar />

        <div>{children}</div>
      </main>
    </>
  );
};
